### ISSUE TITLE
[Feature] Add a symlink also to the vendor package

### ISSUE THREAD

**Issue by pionl** [Letudiant/composer-shared-package-plugin#14]
Hi,

thank you for this great package, helps a lot 👍  Is it possible to create also a symlink in the vendor package?

```
vendor/pion/package (symlink) <-- new
vendor-shared/pion/package/ (symlink)
```

In the production/development I need to use also a less/images from the package. Currently, I just include it from the vendor-shared, but when I will use it in production the paths will be incorrect.

Thank you,

**Comment by Divi** [comment]
Hello @pionl 

This it not the purpose of this package : `vendor` directory should not be a symlink.  
Your real problem is the path in different environments : dev & prod.

You should set an environment variable like `APP_ENV` with `dev` or `prod` and change your file path between the `vendor-shared` or `vendor` directory by calling `getenv('APP_ENV')` function.

**Comment by pionl** [comment]
Hi @Divi, thank you for your response. You are of course right, unfortunately I'm having troubles to pass a variable to the less (the path variable gets a spaces between / when using in the import statement).

Will try to find a way.

Best regards,
Martin.
